# Generated by Django 3.0.8 on 2020-09-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_userdata_hospitalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='hospitalid',
            field=models.SlugField(primary_key=True, serialize=False, unique=True),
        ),
    ]
