# Generated by Django 3.0.8 on 2020-09-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_auto_20200918_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='hospitalid',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
