# Generated by Django 3.0.8 on 2020-09-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_auto_20200919_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='hospitalid',
            field=models.SlugField(primary_key=True, serialize=False, unique=True),
        ),
    ]
